import { PokemonTypeMap } from '@/interfaces'

export const types: PokemonTypeMap = {
  normal: {
    name: 'normal',
    color: 'rgb(137,143,150)',
    doubleDamageFrom: ['fighting'],
    doubleDamageTo: [],
    noDamageFrom: ['ghost'],
    noDamageTo: ['ghost'],
    halfDamageTo: ['rock', 'steel'],
    halfDamageFrom: [],
  },
  fighting: {
    name: 'fighting',
    color: 'rgb(190,75,106)',
    doubleDamageFrom: ['flying', 'psychic', 'fairy'],
    doubleDamageTo: ['normal', 'rock', 'steel', 'ice', 'dark'],
    noDamageFrom: [],
    noDamageTo: ['ghost'],
    halfDamageTo: ['flying', 'poison', 'bug', 'psychic', 'fairy'],
    halfDamageFrom: ['rock', 'bug', 'dark'],
  },
  flying: {
    name: 'flying',
    color: 'rgb(147,168,217)',
    doubleDamageFrom: ['rock', 'electric', 'ice'],
    doubleDamageTo: ['fighting', 'bug', 'grass'],
    noDamageFrom: ['ground'],
    noDamageTo: [],
    halfDamageTo: ['rock', 'steel', 'electric'],
    halfDamageFrom: ['fighting', 'bug', 'grass'],
  },
  poison: {
    name: 'poison',
    color: 'rgb(162,111,195)',
    doubleDamageFrom: ['ground', 'psychic'],
    doubleDamageTo: ['grass', 'fairy'],
    noDamageFrom: [],
    noDamageTo: ['steel'],
    halfDamageTo: ['poison', 'ground', 'rock', 'ghost'],
    halfDamageFrom: ['fighting', 'poison', 'bug', 'grass', 'fairy'],
  },
  ground: {
    name: 'ground',
    color: 'rgb(204,123,80)',
    doubleDamageFrom: ['water', 'grass', 'ice'],
    doubleDamageTo: ['poison', 'rock', 'steel', 'fire', 'electric'],
    noDamageFrom: ['electric'],
    noDamageTo: ['flying'],
    halfDamageTo: ['bug', 'grass'],
    halfDamageFrom: ['poison', 'rock'],
  },
  rock: {
    name: 'rock',
    color: 'rgb(196,183,144)',
    doubleDamageFrom: ['fighting', 'ground', 'steel', 'water', 'grass'],
    doubleDamageTo: ['flying', 'bug', 'fire', 'ice'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['fighting', 'ground', 'steel'],
    halfDamageFrom: ['normal', 'flying', 'poison', 'fire'],
  },
  bug: {
    name: 'bug',
    color: 'rgb(154,191,73)',
    doubleDamageFrom: ['flying', 'rock', 'fire'],
    doubleDamageTo: ['grass', 'psychic', 'dark'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['fighting', 'flying', 'poison', 'ghost', 'steel', 'fire', 'fairy'],
    halfDamageFrom: ['fighting', 'ground', 'grass'],
  },
  ghost: {
    name: 'ghost',
    color: 'rgb(86,105,167)',
    doubleDamageFrom: ['ghost', 'dark'],
    doubleDamageTo: ['ghost', 'psychic'],
    noDamageFrom: ['normal', 'fighting'],
    noDamageTo: ['normal'],
    halfDamageTo: ['dark'],
    halfDamageFrom: ['poison', 'bug'],
  },
  steel: {
    name: 'steel',
    color: 'rgb(102,141,159)',
    doubleDamageFrom: ['fighting', 'ground', 'fire'],
    doubleDamageTo: ['rock', 'ice', 'fairy'],
    noDamageFrom: ['poison'],
    noDamageTo: [],
    halfDamageTo: ['steel', 'fire', 'water', 'electric'],
    halfDamageFrom: ['normal', 'flying', 'rock', 'bug', 'steel', 'grass', 'psychic', 'ice', 'dragon', 'fairy'],
  },
  fire: {
    name: 'fire',
    color: 'rgb(242,160,98)',
    doubleDamageFrom: ['ground', 'rock', 'water'],
    doubleDamageTo: ['bug', 'steel', 'grass', 'ice'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['rock', 'fire', 'water', 'dragon'],
    halfDamageFrom: ['bug', 'steel', 'fire', 'grass', 'ice', 'fairy'],
  },
  water: {
    name: 'water',
    color: 'rgb(92,143,207)',
    doubleDamageFrom: ['grass', 'electric'],
    doubleDamageTo: ['ground', 'rock', 'fire'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['water', 'grass', 'dragon'],
    halfDamageFrom: ['steel', 'fire', 'water', 'ice'],
  },
  grass: {
    name: 'grass',
    color: 'rgb(121,184,102)',
    doubleDamageFrom: ['flying', 'poison', 'bug', 'fire', 'ice'],
    doubleDamageTo: ['ground', 'rock', 'water'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['flying', 'poison', 'bug', 'steel', 'fire', 'grass', 'dragon'],
    halfDamageFrom: ['ground', 'water', 'grass', 'electric'],
  },
  electric: {
    name: 'electric',
    color: 'rgb(239,210,90)',
    doubleDamageFrom: ['ground'],
    doubleDamageTo: ['flying', 'water'],
    noDamageFrom: [],
    noDamageTo: ['ground'],
    halfDamageTo: ['grass', 'electric', 'dragon'],
    halfDamageFrom: ['flying', 'steel', 'electric'],
  },
  psychic: {
    name: 'psychic',
    color: 'rgb(232,121,122)',
    doubleDamageFrom: ['bug', 'ghost', 'dark'],
    doubleDamageTo: ['fighting', 'poison'],
    noDamageFrom: [],
    noDamageTo: ['dark'],
    halfDamageTo: ['steel', 'psychic'],
    halfDamageFrom: ['fighting', 'psychic'],
  },
  ice: {
    name: 'ice',
    color: 'rgb(138,204,192)',
    doubleDamageFrom: ['fighting', 'rock', 'steel', 'fire'],
    doubleDamageTo: ['flying', 'ground', 'grass', 'dragon'],
    noDamageFrom: [],
    noDamageTo: [],
    halfDamageTo: ['steel', 'fire', 'water', 'ice'],
    halfDamageFrom: ['ice'],
  },
  dragon: {
    name: 'dragon',
    color: 'rgb(45,109,190)',
    doubleDamageFrom: ['ice', 'dragon', 'fairy'],
    doubleDamageTo: ['dragon'],
    noDamageFrom: [],
    noDamageTo: ['fairy'],
    halfDamageTo: ['steel'],
    halfDamageFrom: ['fire', 'water', 'grass', 'electric'],
  },
  dark: {
    name: 'dark',
    color: 'rgb(89,83,101)',
    doubleDamageFrom: ['fighting', 'bug', 'fairy'],
    doubleDamageTo: ['ghost', 'psychic'],
    noDamageFrom: ['psychic'],
    noDamageTo: [],
    halfDamageTo: ['fighting', 'dark', 'fairy'],
    halfDamageFrom: ['ghost', 'dark'],
  },
  fairy: {
    name: 'fairy',
    color: 'rgb(223,148,225)',
    doubleDamageFrom: ['poison', 'steel'],
    doubleDamageTo: ['fighting', 'dragon', 'dark'],
    noDamageFrom: ['dragon'],
    noDamageTo: [],
    halfDamageTo: ['poison', 'steel', 'fire'],
    halfDamageFrom: ['fighting', 'bug', 'dark'],
  },
}
